BIG_WIN_MULTI = 50
MIN_WIN_LOG = -1
MAX_BET_USD = 1
SMALLEST_BET = 0.00000001
STAKE_GQL_ENDPOINT = 'https://api.stake.com/graphql'
TWITTER_API_KEY=''
TWITTER_API_SECRET=''
TWITTER_BEARER_TOKEN=''

# CAPTCHA BYPASS
STAKE_SITE_KEY = ''
TWO_CAPTCHA_API_KEY = ''